import { Game } from '../types';

export const GAMES: Game[] = [
  {
    id: 'flip7',
    name: 'Flip 7',
    description: 'Piochez des cartes sans dépasser 7 !',
    icon: 'cards-playing-outline',
    image: require('../../image/Flip7.png'),
    color: '#e74c3c',
    accentColor: '#c0392b',
    minPlayers: 2,
    maxPlayers: 8,
  },
  {
    id: 'papayoo',
    name: 'Papayoo',
    description: 'Jeu de cartes : évitez de remporter des plis !',
    icon: 'cards-playing',
    image: require('../../image/papayoo.png'),
    color: '#f39c12',
    accentColor: '#d68910',
    minPlayers: 2,
    maxPlayers: 6,
    lowWins: true,
  },
  {
    id: 'skull-king',
    name: 'Skull King',
    description: 'Pariez sur vos plis et dominez les pirates !',
    icon: 'skull-crossbones',
    image: require('../../image/SkullKing.png'),
    color: '#2980b9',
    accentColor: '#1a5276',
    minPlayers: 2,
    maxPlayers: 8,
  },
  {
    id: 'tarot',
    name: 'Tarot',
    description: 'Prenez, défendez, remportez les plis !',
    icon: 'cards-heart',
    image: require('../../image/tarot.png'),
    color: '#c0392b',
    accentColor: '#922b21',
    minPlayers: 3,
    maxPlayers: 5,
  },
  {
    id: 'farway',
    name: 'Farway',
    description: 'Explorez des régions et trouvez des sanctuaires !',
    icon: 'map-search-outline',
    image: require('../../image/faraway.png'),
    color: '#27ae60',
    accentColor: '#1e8449',
    minPlayers: 2,
    maxPlayers: 5,
  },
  {
    id: 'skyjo',
    name: 'Skyjo',
    description: 'Ayez le score le plus bas quand un joueur atteint 100 points !',
    icon: 'card-multiple-outline',
    image: require('../../image/Skyjo.png'),
    color: '#00ACC1',
    accentColor: '#007C91',
    minPlayers: 2,
    maxPlayers: 8,
    lowWins: true,
  },
  {
    id: '6quiprend',
    name: '6 qui prend !',
    description: 'Évitez de ramasser des têtes de bœuf — le plus bas gagne !',
    icon: 'cow',
    image: require('../../image/6quiprend-.png'),
    color: '#c0392b',
    accentColor: '#922b21',
    minPlayers: 2,
    maxPlayers: 10,
    lowWins: true,
  },
  {
    id: 'ligretto',
    name: 'Ligretto',
    description: 'Marquez des points chaque manche — le premier à 99 gagne !',
    icon: 'cards-playing-outline',
    image: require('../../image/ligretto.png'),
    color: '#e53935',
    accentColor: '#b71c1c',
    minPlayers: 2,
    maxPlayers: 4,
  },
  {
    id: 'classic',
    name: 'Compteur classique',
    description: 'Compteur de points universel pour n\'importe quel jeu.',
    icon: 'counter',
    color: '#546e7a',
    accentColor: '#37474f',
    minPlayers: 1,
    maxPlayers: 10,
  },
  {
    id: 'catan',
    name: 'Catan',
    description: 'Bâtissez, commercez et atteignez 10 points de victoire !',
    icon: 'hexagon-multiple',
    image: require('../../image/catan.png'),
    color: '#e67e22',
    accentColor: '#ca6f1e',
    minPlayers: 3,
    maxPlayers: 4,
  },
  {
    id: '7wonders',
    name: '7 Wonders',
    description: 'Bâtissez la civilisation la plus rayonnante de l\'Antiquité !',
    icon: 'pillar',
    image: require('../../image/7Wonders.png'),
    color: '#7D3C98',
    accentColor: '#5B2C6F',
    minPlayers: 2,
    maxPlayers: 7,
  },
];
